In [1]:
import numpy as np
import pandas as pd

# Step 1: Loading the CSV dataset into a Pandas DataFrame

In [4]:
df = pd.read_csv('Combined_dataset.csv')
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

# Step 2: Exploring data

In [5]:
df.head(5)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [6]:
df.tail(5)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [9]:
df.shape

(1000, 24)

In [12]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [17]:
df.dtypes

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

# Step 3: Handling missing values

In [22]:
df.isnull()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,True,False,False,False
996,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,True,False,False,False
997,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,True,True,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,True,False,False,False
999,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,True,True,False,False,False,False

In [23]:
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [55]:
df_filled = df.ffill()

In [56]:
df_filled.isnull()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [57]:
df_filled.isnull().sum()

product_id                 0
title                      0
product_description        0
rating                     0
ratings_count              0
initial_price              0
discount                   0
final_price                0
currency                   0
images                     0
delivery_options           0
product_details            0
breadcrumbs                0
product_specifications     0
amount_of_stars            0
what_customers_said       23
seller_name                5
sizes                      0
videos                     0
seller_information         5
variations                 0
best_offer                 0
more_offers                0
category                   0
dtype: int64

In [74]:
nan_value = float("NaN")
df_filled.replace("", nan_value, inplace=True)
df_filled.dropna()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,final_amount
23,17372928,The Souled Store,Men Blue & White Abstract Printed Boxers,4.5,22,799,54.0,"""₹367.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"[{""percentage"":""100"",""value_name"":""Fit, Just R...",THE███ULE███TOR█████████D.,"[{""size"":""S"",""value"":""30.0in"",""value_name"":""To...","[""https://videos.myntassets.com/assets/videos/...","F6 ███02,███umi█████████dus███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",boxers,431.46
24,15115018,Jockey,Non-Wired Non-Padded Combed Cotton Workout Bra...,4.4,1582,579,54.0,"""₹579.00""",INR,http://assets.myntassets.com/assets/images/151...,...,"[{""percentage"":""100"",""value_name"":""Fit, Just R...",Tru███m R███il,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""Ov...","[""https://videos.myntassets.com/assets/videos/...",Sho███o. ███-10█████████enu███████████████████...,"[{},{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bra,312.66
25,22063882,GROVERSONS Paris Beauty,Non Padded Cotton Seamless Non-Wired T-shirt Bra,4.0,25,399,25.0,"""₹299.00""",INR,http://assets.myntassets.com/assets/images/220...,...,"[{""percentage"":""100"",""value_name"":""Fit, Just R...",Gro███son███ppa█████████Ltd███,"[{""size"":""30B"",""value"":""31.0in"",""value_name"":""...","[""https://videos.myntassets.com/assets/videos/...","sec███ A-███Plo█████████, I███████████████████...","[{},{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bra,99.75
26,19219450,Susie,Black Solid Cotton T-Shirt Bra - Anti-Odour,4.3,12,749,50.0,"""₹374.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"[{""percentage"":""100"",""value_name"":""Fit, Just R...",GEN███AD ███AIL█████████LIM██████,"[{""size"":""30B"",""value"":""31.0in to 32.0in"",""val...","[""https://videos.myntassets.com/assets/videos/...",2ND███OOR███O 1█████████MAL███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bra,374.50
27,22196924,Zivame,Underwired Lightly Padded Pushup Bra,4.3,118,999,50.0,"""₹499.00""",INR,http://assets.myntassets.com/assets/images/221...,...,"[{""percentage"":""100"",""value_name"":""Fit, Just R...",MIL███AR ███AIL█████████LIM██████,"[{""size"":""30A"",""value"":""31.0in"",""value_name"":""...","[""https://videos.myntassets.com/assets/videos/...",MIL███TAR███TAI█████████ LI███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bra,499.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Br ███erp███es,"[{""size"":""Onesize""}]","[""pi-13698258""]",Kha███ no███122█████████lhi██████████████████,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,5945.00
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Br ███erp███es,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",Kha███ no███122█████████lhi██████████████████,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,4005.00
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Br ███erp███es,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",Kha███ no███122█████████lhi██████████████████,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,3975.00
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Tru███m R███il,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",Sho███o. ███-10█████████enu███████████████████...,"[{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches,659.00
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Tru███m R███il,"[{""size"":""Medium""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",Sho███o. ███-10█████████enu███████████████████...,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats,216.69

# Step 4: Performimg basic operations

In [75]:
# Column selection
df_filled[['product_id', 'title']]

     product_id           title
0       8376765     Lino Perros
1       9136281  Tommy Hilfiger
2      17633752           Lavie
3       1376949          F Gear
4      13939916       MYTRIDENT
..          ...             ...
995    13698258           KREDO
996    16896006           GUESS
997     1708108        GIORDANO
998    19280114        Fastrack
999    18601682         BOLDFIT

[1000 rows x 2 columns]

In [76]:
# filtering rows
df_filter = df_filled[df['rating'] > 4.0]

In [77]:
df_filter

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,final_amount
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1014.65
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1949.35
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,871.00
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,492.83
5,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399,17.0,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/171...,...,NaN,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",Pra███yat███fra█████████PVT███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bathroom-accessories,237.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,2466414,Daniel Klein,Women Brown Analogue Watch DK11467-6,4.4,940,6950,53.0,"""₹3,266.00""",INR,http://assets.myntassets.com/assets/images/246...,...,"[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",DES███ER ███GRE█████████IA ██████,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...","Fir███Flo███ Pl█████████, I███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches,3683.50
992,11791782,CASIO,Youth Digital Women Red Digital Watch I117 DW-...,4.6,29,3595,10.0,"""₹3,235.00""",INR,http://assets.myntassets.com/assets/images/117...,...,"[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Fla███ech███tai███,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...","3rd███165███th █████████, s███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches,359.50
994,8481603,French Connection,Women Silver-Toned Analogue Watch FCN0001B,4.5,149,6250,70.0,"""₹6,250.00""",INR,http://assets.myntassets.com/assets/images/848...,...,"[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Br ███erp███es,"[{""size"":""Onesize""}]","[""rw-8481603_cae700"",""https://videos.myntasset...",Kha███ no███122█████████lhi██████████████████,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,4375.00
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Br ███erp███es,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",Kha███ no███122█████████lhi██████████████████,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,4005.00
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Tru███m R███il,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",Sho███o. ███-10█████████enu███████████████████...,"[{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches,659.00

# Step 5: Removing duplicates

In [78]:
df_filled.drop_duplicates()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,final_amount
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,2317.10
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1014.65
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1949.35
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,871.00
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,492.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Br ███erp███es,"[{""size"":""Onesize""}]","[""pi-13698258""]",Kha███ no███122█████████lhi██████████████████,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,5945.00
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Br ███erp███es,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",Kha███ no███122█████████lhi██████████████████,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,4005.00
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Br ███erp███es,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",Kha███ no███122█████████lhi██████████████████,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,3975.00
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Tru███m R███il,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",Sho███o. ███-10█████████enu███████████████████...,"[{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches,659.00
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Tru███m R███il,"[{""size"":""Medium""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",Sho███o. ███-10█████████enu███████████████████...,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats,216.69

# Step 6: Creating a new column

In [79]:
#  final_amount = initial_price * discount [as there is no quantity column in dataset]
df_filled['final_amount'] = df_filled['initial_price'] * (df_filled['discount'] / 100)

In [80]:
df_filled

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,final_amount
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,2317.10
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1014.65
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1949.35
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,871.00
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,492.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Br ███erp███es,"[{""size"":""Onesize""}]","[""pi-13698258""]",Kha███ no███122█████████lhi██████████████████,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,5945.00
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Br ███erp███es,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",Kha███ no███122█████████lhi██████████████████,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,4005.00
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Br ███erp███es,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",Kha███ no███122█████████lhi██████████████████,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,3975.00
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Tru███m R███il,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",Sho███o. ███-10█████████enu███████████████████...,"[{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches,659.00
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Tru███m R███il,"[{""size"":""Medium""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",Sho███o. ███-10█████████enu███████████████████...,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats,216.69

# Step 7: Saving the cleaned dataset as a new CSV file

In [81]:
df_filled.to_csv('cleaned_data.csv', index = False)